version: '3.8'  # Version of Docker Compose

services:
  app:
    build:
      context: .  # The directory containing your app and Dockerfile
    ports:
      - "8081:8081"  # Maps port 5000 on the host to port 5000 on the container
    depends_on:
      - postgres_db  # Ensure the database is started before the app
      - mycache  # Ensure Redis starts before the app
    environment:
      - APP_ENV=development
    networks:
      - app-network


  postgres_db:
    image: postgres  # PostgreSQL version (you can adjust it as needed)
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Exposes PostgreSQL on port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persists PostgreSQL data using a Docker volume
    networks:
      - app-network

  mycache:
    image: "redis"  # Use a lightweight Redis image
    hostname: redis-db
    ports:
      - "6379:6379"  # Exposes Redis on port 6379
    command: redis-server --port 6379 --bind 0.0.0.0 --protected-mode no
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: